### ISSUE TITLE
你好，请求帮助，同样的模块代码无法高亮

### ISSUE THREAD

**Issue by chopperkuang** [MForever78/MForever78.github.io#1]
今天看了你的博客，非常喜欢这种风格。
于是我今天也调整了。

但碰到一个问题，我的文章中的代码无法高亮。
即使跟你的配置一样。也不能进行解析。

你是怎么做到的？
谢谢

---

以下我的博客地址和配置

github地址：[chopperkuang](https://github.com/chopperkuang/chopperkuang.github.com)

``` yaml
# Markdown
markdown:  kramdown
kramdown:
  input:  GFM
  syntax_highlighter:  rouge
```
